package com.ntcoverage.seed

data class CouncilSeedEntry(
    val displayName: String,
    val year: Int,
    val yearEnd: Int? = null,
    val century: Int,
    val councilType: String,
    val location: String? = null,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val shortDescription: String? = null,
    val mainTopics: String? = null,
    val keyParticipants: String? = null,
    val numberOfParticipants: Int? = null,
    val wikipediaUrl: String? = null,
    val wikidataId: String? = null,
    val heresyNames: List<String> = emptyList(),
    val fatherNames: List<String> = emptyList(),
    val aliases: List<String> = emptyList()
)

object CouncilsSeedData {
    private fun centuryOf(year: Int): Int = ((year - 1) / 100) + 1

    private fun c(
        displayName: String,
        year: Int,
        councilType: String,
        yearEnd: Int? = null,
        location: String? = null,
        latitude: Double? = null,
        longitude: Double? = null,
        shortDescription: String? = null,
        mainTopics: String? = null,
        keyParticipants: String? = null,
        numberOfParticipants: Int? = null,
        wikipediaUrl: String? = null,
        wikidataId: String? = null,
        heresyNames: List<String> = emptyList(),
        fatherNames: List<String> = emptyList(),
        aliases: List<String> = emptyList()
    ) = CouncilSeedEntry(
        displayName = displayName,
        year = year,
        yearEnd = yearEnd,
        century = centuryOf(year),
        councilType = councilType,
        location = location,
        latitude = latitude,
        longitude = longitude,
        shortDescription = shortDescription,
        mainTopics = mainTopics,
        keyParticipants = keyParticipants,
        numberOfParticipants = numberOfParticipants,
        wikipediaUrl = wikipediaUrl,
        wikidataId = wikidataId,
        heresyNames = heresyNames,
        fatherNames = fatherNames,
        aliases = aliases
    )

    val entries: List<CouncilSeedEntry> = listOf(
        // Ecumenical councils (core)
        c(
            displayName = "First Council of Nicaea",
            year = 325,
            councilType = "ECUMENICAL",
            location = "Nicaea",
            latitude = 40.4281,
            longitude = 29.7210,
            shortDescription = "First ecumenical council called by Emperor Constantine.",
            mainTopics = "Arianism; Nicene Creed; Paschal computation",
            keyParticipants = "Constantine; Athanasius; Hosius of Corduba",
            numberOfParticipants = 318,
            wikipediaUrl = "https://en.wikipedia.org/wiki/First_Council_of_Nicaea",
            wikidataId = "Q184841",
            heresyNames = listOf("Arianism"),
            aliases = listOf("Council of Nicaea", "Nicaea I", "Concilium Nicaenum")
        ),
        c(
            displayName = "First Council of Constantinople",
            year = 381,
            councilType = "ECUMENICAL",
            location = "Constantinople",
            latitude = 41.0082,
            longitude = 28.9784,
            shortDescription = "Second ecumenical council reaffirming Nicaea.",
            mainTopics = "Macedonianism; Arianism; Creed expansion",
            keyParticipants = "Theodosius I; Gregory Nazianzen",
            wikipediaUrl = "https://en.wikipedia.org/wiki/First_Council_of_Constantinople",
            wikidataId = "Q299077",
            heresyNames = listOf("Macedonianism", "Arianism"),
            aliases = listOf("Constantinople I")
        ),
        c(
            displayName = "Council of Ephesus",
            year = 431,
            councilType = "ECUMENICAL",
            location = "Ephesus",
            latitude = 37.9390,
            longitude = 27.3410,
            shortDescription = "Third ecumenical council condemning Nestorianism.",
            mainTopics = "Nestorianism; Theotokos",
            keyParticipants = "Cyril of Alexandria; Nestorius",
            numberOfParticipants = 150,
            wikipediaUrl = "https://en.wikipedia.org/wiki/Council_of_Ephesus",
            wikidataId = "Q184332",
            heresyNames = listOf("Nestorianism"),
            aliases = listOf("Ephesus I")
        ),
        c(
            displayName = "Council of Chalcedon",
            year = 451,
            councilType = "ECUMENICAL",
            location = "Chalcedon",
            latitude = 40.9910,
            longitude = 29.0330,
            shortDescription = "Fourth ecumenical council and Chalcedonian Definition.",
            mainTopics = "Christology; Monophysitism",
            keyParticipants = "Marcian; Anatolius of Constantinople; Leo I (via Tome)",
            numberOfParticipants = 500,
            wikipediaUrl = "https://en.wikipedia.org/wiki/Council_of_Chalcedon",
            wikidataId = "Q170553",
            heresyNames = listOf("Monophysitism"),
            aliases = listOf("Chalcedon")
        ),
        c(
            displayName = "Second Council of Constantinople",
            year = 553,
            councilType = "ECUMENICAL",
            location = "Constantinople",
            latitude = 41.0082,
            longitude = 28.9784,
            shortDescription = "Fifth ecumenical council focused on Three Chapters controversy.",
            mainTopics = "Three Chapters; Christology",
            keyParticipants = "Justinian I; Eutychius of Constantinople",
            wikipediaUrl = "https://en.wikipedia.org/wiki/Second_Council_of_Constantinople",
            wikidataId = "Q188099",
            heresyNames = listOf("Three Chapters"),
            aliases = listOf("Constantinople II")
        ),
        c(
            displayName = "Third Council of Constantinople",
            year = 680,
            yearEnd = 681,
            councilType = "ECUMENICAL",
            location = "Constantinople",
            latitude = 41.0082,
            longitude = 28.9784,
            shortDescription = "Sixth ecumenical council condemning Monothelitism.",
            mainTopics = "Monothelitism; Monoenergism",
            keyParticipants = "Constantine IV; Agatho of Rome (letters)",
            wikipediaUrl = "https://en.wikipedia.org/wiki/Third_Council_of_Constantinople",
            wikidataId = "Q187194",
            heresyNames = listOf("Monothelitism", "Monoenergism"),
            aliases = listOf("Constantinople III")
        ),
        c(
            displayName = "Second Council of Nicaea",
            year = 787,
            councilType = "ECUMENICAL",
            location = "Nicaea",
            latitude = 40.4281,
            longitude = 29.7210,
            shortDescription = "Seventh ecumenical council restoring icon veneration.",
            mainTopics = "Iconoclasm; veneration of icons",
            keyParticipants = "Empress Irene; Tarasius",
            numberOfParticipants = 350,
            wikipediaUrl = "https://en.wikipedia.org/wiki/Second_Council_of_Nicaea",
            wikidataId = "Q187201",
            heresyNames = listOf("Iconoclasm"),
            aliases = listOf("Nicaea II")
        ),
        c(
            displayName = "Fourth Council of Constantinople",
            year = 869,
            yearEnd = 870,
            councilType = "ECUMENICAL",
            location = "Constantinople",
            latitude = 41.0082,
            longitude = 28.9784,
            shortDescription = "Council recognized as ecumenical in Catholic tradition.",
            mainTopics = "Photian schism; ecclesiastical jurisdiction",
            keyParticipants = "Basil I; Hadrian II legates",
            wikipediaUrl = "https://en.wikipedia.org/wiki/Fourth_Council_of_Constantinople_(Roman_Catholic)",
            wikidataId = "Q180322",
            aliases = listOf("Constantinople IV")
        ),

        // Pre-Nicene and early regional councils
        c("Council of Jerusalem", 50, "LOCAL", location = "Jerusalem", wikipediaUrl = "https://en.wikipedia.org/wiki/Council_of_Jerusalem", aliases = listOf("Apostolic Council")),
        c("Council of Rome (155)", 155, "LOCAL", location = "Rome"),
        c("Council of Ephesus (193)", 193, "LOCAL", location = "Ephesus"),
        c("Council of Rome (193)", 193, "LOCAL", location = "Rome"),
        c("Council of Carthage (251)", 251, "REGIONAL", location = "Carthage", heresyNames = listOf("Novatianism")),
        c("Synod of Rome (251)", 251, "LOCAL", location = "Rome", heresyNames = listOf("Novatianism")),
        c("Council of Iconium", 258, "REGIONAL", location = "Iconium"),
        c("Council of Antioch (264)", 264, "REGIONAL", location = "Antioch", heresyNames = listOf("Paul of Samosata")),
        c("Council of Antioch (268)", 268, "REGIONAL", location = "Antioch"),
        c("Councils of Arabia", 246, "REGIONAL", yearEnd = 247, location = "Arabia"),
        c("Synod of Elvira", 306, "REGIONAL", location = "Elvira"),
        c("Council of Carthage (311)", 311, "REGIONAL", location = "Carthage"),
        c("Synod of Ancyra", 314, "REGIONAL", location = "Ancyra", wikipediaUrl = "https://en.wikipedia.org/wiki/Synod_of_Ancyra"),
        c("Synod of Arles (314)", 314, "REGIONAL", location = "Arles", wikipediaUrl = "https://en.wikipedia.org/wiki/Synod_of_Arles_(314)"),
        c("Synod of Neocaesarea", 314, "REGIONAL", location = "Neocaesarea"),
        c("Synod of Antioch (324)", 324, "REGIONAL", location = "Antioch"),
        c("Council of Tyre", 335, "REGIONAL", location = "Tyre"),
        c("Synod of Gangra", 340, "REGIONAL", location = "Gangra"),
        c("Council of Sardica", 343, "REGIONAL", location = "Sardica"),
        c("Council of Sirmium", 351, "REGIONAL", location = "Sirmium", heresyNames = listOf("Arianism")),
        c("Council of Ariminum", 359, "REGIONAL", location = "Ariminum"),
        c("Council of Seleucia", 359, "REGIONAL", location = "Seleucia"),
        c("Council of Alexandria (362)", 362, "REGIONAL", location = "Alexandria"),
        c("Synod of Laodicea", 363, "REGIONAL", location = "Laodicea"),
        c("Council of Aquileia", 381, "REGIONAL", location = "Aquileia"),
        c("Council of Saragossa", 380, "REGIONAL", location = "Saragossa"),

        // Carthage sequence
        c("Council of Carthage I", 394, "REGIONAL", location = "Carthage"),
        c("Council of Carthage II", 397, "REGIONAL", location = "Carthage"),
        c("Council of Carthage III", 397, "REGIONAL", location = "Carthage"),
        c("Council of Carthage IV", 399, "REGIONAL", location = "Carthage"),
        c("Council of Carthage V", 401, "REGIONAL", location = "Carthage"),
        c("Council of Carthage VI", 401, "REGIONAL", location = "Carthage"),
        c("Council of Milevis", 402, "REGIONAL", location = "Milevis"),
        c("Council of Diospolis", 415, "REGIONAL", location = "Diospolis"),
        c("Council of Carthage XVII", 419, "REGIONAL", location = "Carthage"),

        // Toledo councils
        c("First Council of Toledo", 400, "REGIONAL", location = "Toledo", wikipediaUrl = "https://en.wikipedia.org/wiki/First_Council_of_Toledo"),
        c("Second Council of Toledo", 527, "REGIONAL", location = "Toledo"),
        c("Third Council of Toledo", 589, "REGIONAL", location = "Toledo"),
        c("Fourth Council of Toledo", 633, "REGIONAL", location = "Toledo"),
        c("Fifth Council of Toledo", 636, "REGIONAL", location = "Toledo"),
        c("Sixth Council of Toledo", 638, "REGIONAL", location = "Toledo"),
        c("Seventh Council of Toledo", 646, "REGIONAL", location = "Toledo"),
        c("Eighth Council of Toledo", 653, "REGIONAL", location = "Toledo"),
        c("Ninth Council of Toledo", 655, "REGIONAL", location = "Toledo"),
        c("Tenth Council of Toledo", 656, "REGIONAL", location = "Toledo"),
        c("Eleventh Council of Toledo", 675, "REGIONAL", location = "Toledo"),
        c("Twelfth Council of Toledo", 681, "REGIONAL", location = "Toledo"),
        c("Thirteenth Council of Toledo", 683, "REGIONAL", location = "Toledo"),
        c("Fourteenth Council of Toledo", 684, "REGIONAL", location = "Toledo"),
        c("Fifteenth Council of Toledo", 688, "REGIONAL", location = "Toledo"),
        c("Sixteenth Council of Toledo", 693, "REGIONAL", location = "Toledo"),
        c("Seventeenth Council of Toledo", 694, "REGIONAL", location = "Toledo"),

        // Gaul / Hispania / Italia / Britannia / Armenia
        c("Council of Orange I", 441, "REGIONAL", location = "Orange"),
        c("Council of Orange II", 529, "REGIONAL", location = "Orange"),
        c("Council of Agde", 506, "REGIONAL", location = "Agde"),
        c("Council of Arles (524)", 524, "REGIONAL", location = "Arles"),
        c("Council of Carpentras", 527, "REGIONAL", location = "Carpentras"),
        c("Council of Vaison", 529, "REGIONAL", location = "Vaison"),
        c("First Council of Orléans", 511, "REGIONAL", location = "Orleans"),
        c("Second Council of Orléans", 533, "REGIONAL", location = "Orleans"),
        c("Third Council of Orléans", 538, "REGIONAL", location = "Orleans"),
        c("Fourth Council of Orléans", 541, "REGIONAL", location = "Orleans"),
        c("Fifth Council of Orléans", 549, "REGIONAL", location = "Orleans"),
        c("Sixth Council of Orléans", 549, "REGIONAL", location = "Orleans"),
        c("First Council of Braga", 561, "REGIONAL", location = "Braga"),
        c("Second Council of Braga", 572, "REGIONAL", location = "Braga"),
        c("Council of Lleida", 546, "REGIONAL", location = "Lleida"),
        c("Synod of Dvin I", 506, "REGIONAL", location = "Dvin"),
        c("Synod of Dvin II", 554, "REGIONAL", location = "Dvin"),
        c("Synod of Dvin III", 645, "REGIONAL", location = "Dvin"),
        c("Council of Paris (614)", 614, "REGIONAL", location = "Paris"),
        c("Council of Whitby", 664, "REGIONAL", location = "Whitby"),
        c("Council of Hatfield", 679, "REGIONAL", location = "Hatfield"),
        c("Lateran Council (649)", 649, "REGIONAL", location = "Rome"),
        c("Quinisext Council (Trullo)", 692, "REGIONAL", location = "Constantinople", aliases = listOf("Council in Trullo")),
        c("Council of Hieria", 754, "REGIONAL", location = "Constantinople"),
        c("Council of Frankfurt", 794, "REGIONAL", location = "Frankfurt"),
        c("Council of Paris (825)", 825, "REGIONAL", location = "Paris"),
        c("Council of Aachen", 809, "REGIONAL", location = "Aachen"),
        c("Council of Quierzy", 853, "REGIONAL", location = "Quierzy"),
        c("Council of Worms (868)", 868, "REGIONAL", location = "Worms"),
        c("Photian Council of Constantinople", 879, "REGIONAL", location = "Constantinople"),
        c("Council of Tribur", 895, "REGIONAL", location = "Tribur"),
        c("Council of Hohenaltheim", 916, "REGIONAL", location = "Hohenaltheim"),
        c("First Council of Split", 925, "REGIONAL", location = "Split"),
        c("Second Council of Split", 928, "REGIONAL", location = "Split"),
        c("Council of Koblenz", 922, "REGIONAL", location = "Koblenz"),
        c("Council of Ingelheim", 948, "REGIONAL", location = "Ingelheim"),
        c("Council of Ravenna (968)", 968, "REGIONAL", location = "Ravenna"),
        c("Synod of Charroux", 989, "LOCAL", location = "Charroux"),
        c("Synod of Narbonne", 990, "LOCAL", location = "Narbonne"),
        c("Synod of Le Puy", 990, "LOCAL", location = "Le Puy"),
        c("Council of Limoges", 994, "LOCAL", location = "Limoges"),
        c("Council of Anse", 994, "LOCAL", location = "Anse"),
        c("Council of Poitiers", 998, "LOCAL", location = "Poitiers"),
        c("Council of Pavia (997)", 997, "LOCAL", location = "Pavia"),
        c("Council of Rome (998)", 998, "LOCAL", location = "Rome"),
        c("Council of Reims (991)", 991, "LOCAL", location = "Reims"),

        // Additional late-antique and early-medieval local synods for dataset breadth
        c("Council of Milan (355)", 355, "LOCAL", location = "Milan"),
        c("Council of Rimini", 359, "LOCAL", location = "Rimini"),
        c("Council of Constantinople (360)", 360, "LOCAL", location = "Constantinople"),
        c("Council of Antioch (363)", 363, "LOCAL", location = "Antioch"),
        c("Council of Rome (382)", 382, "LOCAL", location = "Rome"),
        c("Council of Hippo", 393, "LOCAL", location = "Hippo"),
        c("Council of Turin", 398, "LOCAL", location = "Turin"),
        c("Council of Seleucia-Ctesiphon", 410, "REGIONAL", location = "Seleucia-Ctesiphon"),
        c("Council of Orange (529 local preparatory)", 529, "LOCAL", location = "Orange"),
        c("Council of Clermont (535)", 535, "LOCAL", location = "Clermont"),
        c("Council of Mâcon I", 581, "LOCAL", location = "Macon"),
        c("Council of Mâcon II", 585, "LOCAL", location = "Macon"),
        c("Council of Seville II", 619, "LOCAL", location = "Seville"),
        c("Council of Rome (649 preparatory)", 648, "LOCAL", location = "Rome"),
        c("Council of Clovesho (747)", 747, "LOCAL", location = "Clovesho"),
        c("Council of Clovesho (803)", 803, "LOCAL", location = "Clovesho"),
        c("Council of Mainz (813)", 813, "LOCAL", location = "Mainz"),
        c("Council of Mainz (847)", 847, "LOCAL", location = "Mainz"),
        c("Council of Pavia (850)", 850, "LOCAL", location = "Pavia"),
        c("Council of Metz", 888, "LOCAL", location = "Metz"),
        c("Council of Trosly", 909, "LOCAL", location = "Trosly"),
        c("Council of Chelsea", 787, "LOCAL", location = "Chelsea"),
        c("Council of Benevento", 694, "LOCAL", location = "Benevento"),
        c("Council of Toledo (local 610)", 610, "LOCAL", location = "Toledo"),
        c("Council of Narbonne (589)", 589, "LOCAL", location = "Narbonne"),
        c("Council of Gerona", 517, "LOCAL", location = "Gerona"),
        c("Council of Tarragona", 516, "LOCAL", location = "Tarragona"),
        c("Council of Braga (675 local)", 675, "LOCAL", location = "Braga"),
        c("Council of Chalon", 647, "LOCAL", location = "Chalon"),
        c("Council of Rouen", 650, "LOCAL", location = "Rouen"),
        c("Council of York", 786, "LOCAL", location = "York"),
        c("Council of Ponthion", 876, "LOCAL", location = "Ponthion"),
        c("Council of Douzy", 871, "LOCAL", location = "Douzy"),
        c("Council of Trebur (895 local)", 895, "LOCAL", location = "Trebur"),
        c("Council of Saint-Basle", 991, "LOCAL", location = "Saint-Basle"),
        c("Council of Verdun", 947, "LOCAL", location = "Verdun"),
        c("Council of Chiersy", 857, "LOCAL", location = "Chiersy"),
        c("Council of Ravenna (877)", 877, "LOCAL", location = "Ravenna"),
        c("Council of Rome (963)", 963, "LOCAL", location = "Rome"),
        c("Council of Sutri (998)", 998, "LOCAL", location = "Sutri"),
        c("Council of Pavia (968)", 968, "LOCAL", location = "Pavia")
    )
}
