package com.ntcoverage.seed

object BibleBookNamesSeedData {
    data class NameEntry(
        val canonicalName: String,
        val locale: String,
        val name: String
    )

    val entries = listOf(
        // OLD TESTAMENT — pt
        NameEntry("Genesis", "pt", "Gênesis"),
        NameEntry("Exodus", "pt", "Êxodo"),
        NameEntry("Leviticus", "pt", "Levítico"),
        NameEntry("Numbers", "pt", "Números"),
        NameEntry("Deuteronomy", "pt", "Deuteronômio"),
        NameEntry("Joshua", "pt", "Josué"),
        NameEntry("Judges", "pt", "Juízes"),
        NameEntry("Ruth", "pt", "Rute"),
        NameEntry("1 Samuel", "pt", "1 Samuel"),
        NameEntry("2 Samuel", "pt", "2 Samuel"),
        NameEntry("1 Kings", "pt", "1 Reis"),
        NameEntry("2 Kings", "pt", "2 Reis"),
        NameEntry("1 Chronicles", "pt", "1 Crônicas"),
        NameEntry("2 Chronicles", "pt", "2 Crônicas"),
        NameEntry("Ezra", "pt", "Esdras"),
        NameEntry("Nehemiah", "pt", "Neemias"),
        NameEntry("Esther", "pt", "Ester"),
        NameEntry("Job", "pt", "Jó"),
        NameEntry("Psalms", "pt", "Salmos"),
        NameEntry("Proverbs", "pt", "Provérbios"),
        NameEntry("Ecclesiastes", "pt", "Eclesiastes"),
        NameEntry("Song of Solomon", "pt", "Cantares de Salomão"),
        NameEntry("Isaiah", "pt", "Isaías"),
        NameEntry("Jeremiah", "pt", "Jeremias"),
        NameEntry("Lamentations", "pt", "Lamentações"),
        NameEntry("Ezekiel", "pt", "Ezequiel"),
        NameEntry("Daniel", "pt", "Daniel"),
        NameEntry("Hosea", "pt", "Oseias"),
        NameEntry("Joel", "pt", "Joel"),
        NameEntry("Amos", "pt", "Amós"),
        NameEntry("Obadiah", "pt", "Obadias"),
        NameEntry("Jonah", "pt", "Jonas"),
        NameEntry("Micah", "pt", "Miqueias"),
        NameEntry("Nahum", "pt", "Naum"),
        NameEntry("Habakkuk", "pt", "Habacuque"),
        NameEntry("Zephaniah", "pt", "Sofonias"),
        NameEntry("Haggai", "pt", "Ageu"),
        NameEntry("Zechariah", "pt", "Zacarias"),
        NameEntry("Malachi", "pt", "Malaquias"),

        // NEW TESTAMENT — pt
        NameEntry("Matthew", "pt", "Mateus"),
        NameEntry("Mark", "pt", "Marcos"),
        NameEntry("Luke", "pt", "Lucas"),
        NameEntry("John", "pt", "João"),
        NameEntry("Acts", "pt", "Atos"),
        NameEntry("Romans", "pt", "Romanos"),
        NameEntry("1 Corinthians", "pt", "1 Coríntios"),
        NameEntry("2 Corinthians", "pt", "2 Coríntios"),
        NameEntry("Galatians", "pt", "Gálatas"),
        NameEntry("Ephesians", "pt", "Efésios"),
        NameEntry("Philippians", "pt", "Filipenses"),
        NameEntry("Colossians", "pt", "Colossenses"),
        NameEntry("1 Thessalonians", "pt", "1 Tessalonicenses"),
        NameEntry("2 Thessalonians", "pt", "2 Tessalonicenses"),
        NameEntry("1 Timothy", "pt", "1 Timóteo"),
        NameEntry("2 Timothy", "pt", "2 Timóteo"),
        NameEntry("Titus", "pt", "Tito"),
        NameEntry("Philemon", "pt", "Filemom"),
        NameEntry("Hebrews", "pt", "Hebreus"),
        NameEntry("James", "pt", "Tiago"),
        NameEntry("1 Peter", "pt", "1 Pedro"),
        NameEntry("2 Peter", "pt", "2 Pedro"),
        NameEntry("1 John", "pt", "1 João"),
        NameEntry("2 John", "pt", "2 João"),
        NameEntry("3 John", "pt", "3 João"),
        NameEntry("Jude", "pt", "Judas"),
        NameEntry("Revelation", "pt", "Apocalipse"),

        // OLD TESTAMENT — es
        NameEntry("Genesis", "es", "Génesis"),
        NameEntry("Exodus", "es", "Éxodo"),
        NameEntry("Leviticus", "es", "Levítico"),
        NameEntry("Numbers", "es", "Números"),
        NameEntry("Deuteronomy", "es", "Deuteronomio"),
        NameEntry("Joshua", "es", "Josué"),
        NameEntry("Judges", "es", "Jueces"),
        NameEntry("Ruth", "es", "Rut"),
        NameEntry("1 Samuel", "es", "1 Samuel"),
        NameEntry("2 Samuel", "es", "2 Samuel"),
        NameEntry("1 Kings", "es", "1 Reyes"),
        NameEntry("2 Kings", "es", "2 Reyes"),
        NameEntry("1 Chronicles", "es", "1 Crónicas"),
        NameEntry("2 Chronicles", "es", "2 Crónicas"),
        NameEntry("Ezra", "es", "Esdras"),
        NameEntry("Nehemiah", "es", "Nehemías"),
        NameEntry("Esther", "es", "Ester"),
        NameEntry("Job", "es", "Job"),
        NameEntry("Psalms", "es", "Salmos"),
        NameEntry("Proverbs", "es", "Proverbios"),
        NameEntry("Ecclesiastes", "es", "Eclesiastés"),
        NameEntry("Song of Solomon", "es", "Cantar de los Cantares"),
        NameEntry("Isaiah", "es", "Isaías"),
        NameEntry("Jeremiah", "es", "Jeremías"),
        NameEntry("Lamentations", "es", "Lamentaciones"),
        NameEntry("Ezekiel", "es", "Ezequiel"),
        NameEntry("Daniel", "es", "Daniel"),
        NameEntry("Hosea", "es", "Oseas"),
        NameEntry("Joel", "es", "Joel"),
        NameEntry("Amos", "es", "Amós"),
        NameEntry("Obadiah", "es", "Abdías"),
        NameEntry("Jonah", "es", "Jonás"),
        NameEntry("Micah", "es", "Miqueas"),
        NameEntry("Nahum", "es", "Nahúm"),
        NameEntry("Habakkuk", "es", "Habacuc"),
        NameEntry("Zephaniah", "es", "Sofonías"),
        NameEntry("Haggai", "es", "Hageo"),
        NameEntry("Zechariah", "es", "Zacarías"),
        NameEntry("Malachi", "es", "Malaquías"),

        // NEW TESTAMENT — es
        NameEntry("Matthew", "es", "Mateo"),
        NameEntry("Mark", "es", "Marcos"),
        NameEntry("Luke", "es", "Lucas"),
        NameEntry("John", "es", "Juan"),
        NameEntry("Acts", "es", "Hechos"),
        NameEntry("Romans", "es", "Romanos"),
        NameEntry("1 Corinthians", "es", "1 Corintios"),
        NameEntry("2 Corinthians", "es", "2 Corintios"),
        NameEntry("Galatians", "es", "Gálatas"),
        NameEntry("Ephesians", "es", "Efesios"),
        NameEntry("Philippians", "es", "Filipenses"),
        NameEntry("Colossians", "es", "Colosenses"),
        NameEntry("1 Thessalonians", "es", "1 Tesalonicenses"),
        NameEntry("2 Thessalonians", "es", "2 Tesalonicenses"),
        NameEntry("1 Timothy", "es", "1 Timoteo"),
        NameEntry("2 Timothy", "es", "2 Timoteo"),
        NameEntry("Titus", "es", "Tito"),
        NameEntry("Philemon", "es", "Filemón"),
        NameEntry("Hebrews", "es", "Hebreos"),
        NameEntry("James", "es", "Santiago"),
        NameEntry("1 Peter", "es", "1 Pedro"),
        NameEntry("2 Peter", "es", "2 Pedro"),
        NameEntry("1 John", "es", "1 Juan"),
        NameEntry("2 John", "es", "2 Juan"),
        NameEntry("3 John", "es", "3 Juan"),
        NameEntry("Jude", "es", "Judas"),
        NameEntry("Revelation", "es", "Apocalipsis")
    )
}
