package com.ntcoverage.seed

data class CouncilCanonSeedEntry(
    val councilSlug: String,
    val canonNumber: Int,
    val title: String?,
    val canonText: String,
    val topic: String?
)

object CouncilCanonsSeedData {

    val entries: List<CouncilCanonSeedEntry> = listOf(
        // Council of Jerusalem (50) - Apostolic Decree from Acts 15
        CouncilCanonSeedEntry("jerusalem-50", 1, "No circumcision required for Gentiles",
            "Gentile believers are not required to be circumcised or to keep the law of Moses. Salvation is through the grace of the Lord Jesus.",
            "Faith"),
        CouncilCanonSeedEntry("jerusalem-50", 2, "Abstain from things polluted by idols",
            "Abstain from what has been sacrificed to idols.",
            "Diet"),
        CouncilCanonSeedEntry("jerusalem-50", 3, "Abstain from sexual immorality",
            "Abstain from sexual immorality.",
            "Morality"),
        CouncilCanonSeedEntry("jerusalem-50", 4, "Abstain from strangled animals and blood",
            "Abstain from what has been strangled and from blood.",
            "Diet"),

        // First Council of Nicaea (325) - 20 canons
        CouncilCanonSeedEntry("nicaea-325", 1, "Prohibition of kneeling on Sundays and Pentecost",
            "Standing is the normative posture for prayer. Kneeling is forbidden on Sundays and during the fifty days from Easter to Pentecost, as these are festive periods.",
            "Liturgy"),
        CouncilCanonSeedEntry("nicaea-325", 2, "Invalidity of baptism by Paulian heretics",
            "Those baptized by Paulian heretics (followers of Paul of Samosata) must be rebaptized, as their baptism is invalid.",
            "Baptism"),
        CouncilCanonSeedEntry("nicaea-325", 3, "Precedence of bishops and presbyters at Communion",
            "Bishops and presbyters shall receive the Eucharist before deacons when receiving Holy Communion.",
            "Eucharist"),
        CouncilCanonSeedEntry("nicaea-325", 4, "Prohibition of usury among clergy",
            "Bishops, presbyters, and deacons are forbidden to engage in usury.",
            "Clergy conduct"),
        CouncilCanonSeedEntry("nicaea-325", 5, "Excommunication of wandering clergy",
            "Clergy who refuse to return to their home church shall be excommunicated. Ordinations performed by such wandering clergy are null and void.",
            "Clergy discipline"),
        CouncilCanonSeedEntry("nicaea-325", 6, "Prohibition of clergy officiating in other cities",
            "Bishops, presbyters, and deacons shall not wander into neighboring cities to officiate without permission.",
            "Jurisdiction"),
        CouncilCanonSeedEntry("nicaea-325", 7, "Lapsed catechumens",
            "Catechumens who lapsed shall spend three years as hearers before being allowed to become catechumens again.",
            "Penance"),
        CouncilCanonSeedEntry("nicaea-325", 8, "Dying penitents and communion",
            "Those fulfilling penance may receive communion if dying. If they recover, they must complete their penance.",
            "Penance"),
        CouncilCanonSeedEntry("nicaea-325", 9, "Ex-military seeking restoration",
            "Those who left the military but later sought to be restored to their military position shall be excommunicated. Readmission to communion may be granted earlier depending on sincerity of repentance.",
            "Penance"),
        CouncilCanonSeedEntry("nicaea-325", 10, "Mercy toward voluntary lapsed",
            "Mercy is enjoined toward those who lapsed without compulsion, though they do not deserve it.",
            "Penance"),
        CouncilCanonSeedEntry("nicaea-325", 11, "Deposition of undiscovered lapsed elders",
            "Elders who lapsed but were not discovered at the time shall be deposed.",
            "Clergy discipline"),
        CouncilCanonSeedEntry("nicaea-325", 12, "Invalid ordinations without examination",
            "Elders ordained without sufficient examination shall not be recognized.",
            "Ordination"),
        CouncilCanonSeedEntry("nicaea-325", 13, "Agreement with Novatianists",
            "Provision for agreement with the Novatianists, an early sect.",
            "Schism"),
        CouncilCanonSeedEntry("nicaea-325", 14, "Honorary rights of Jerusalem",
            "Recognition of the honorary rights of the see of Jerusalem.",
            "Primacy"),
        CouncilCanonSeedEntry("nicaea-325", 15, "Jurisdiction of Alexandria, Rome, Antioch",
            "Confirmation of ancient customs giving jurisdiction over large regions to the bishops of Alexandria, Rome, and Antioch.",
            "Jurisdiction"),
        CouncilCanonSeedEntry("nicaea-325", 16, "Provincial synods",
            "Two provincial synods shall be held annually.",
            "Synods"),
        CouncilCanonSeedEntry("nicaea-325", 17, "Episcopal ordination",
            "A bishop shall be ordained in the presence of at least three provincial bishops, with confirmation by the metropolitan bishop.",
            "Ordination"),
        CouncilCanonSeedEntry("nicaea-325", 18, "Prohibition of virgines subintroductae",
            "Prohibition of a man and woman who have both taken vows of chastity living together in a chaste partnership (virgines subintroductae, syneisaktism).",
            "Chastity"),
        CouncilCanonSeedEntry("nicaea-325", 19, "Minimum term for catechumens",
            "Establishment of a minimum term of instruction for catechumens before baptism.",
            "Baptism"),
        CouncilCanonSeedEntry("nicaea-325", 20, "Prohibition of self-castration for clergy",
            "Those who have castrated themselves are forbidden from the clergy.",
            "Ordination"),

        // First Council of Constantinople (381) - 7 canons (traditionally; some sources list more)
        CouncilCanonSeedEntry("constantinople-381", 1, "Faith of Nicaea",
            "The faith of the 318 fathers at Nicaea shall remain inviolate. Heresies of the Eunomians, Arians, and Macedonians are anathematized.",
            "Faith"),
        CouncilCanonSeedEntry("constantinople-381", 2, "Diocesan boundaries",
            "Bishops shall not extend their authority to churches outside their own boundaries.",
            "Jurisdiction"),
        CouncilCanonSeedEntry("constantinople-381", 3, "Constantinople as second see",
            "The bishop of Constantinople shall have the primacy of honor after the bishop of Rome, because Constantinople is the New Rome.",
            "Primacy"),
        CouncilCanonSeedEntry("constantinople-381", 4, "Maximus the Cynic",
            "Maximus the Cynic and his ordinations are declared invalid.",
            "Ordination"),
        CouncilCanonSeedEntry("constantinople-381", 5, "Western and Eastern creeds",
            "Regarding the tome of the Western bishops: the faith of the 150 fathers at Constantinople is affirmed.",
            "Faith"),
        CouncilCanonSeedEntry("constantinople-381", 6, "Heresies",
            "Various heresies including Eunomians, Arians, and others are anathematized.",
            "Heresy"),
        CouncilCanonSeedEntry("constantinople-381", 7, "Reception of heretics",
            "Rules for the reception of those returning from heresy, with varying requirements based on the heresy.",
            "Penance"),

        // Council of Ephesus (431) - 8 canons
        CouncilCanonSeedEntry("ephesus-431", 1, "Nicene Creed",
            "No one shall be permitted to produce or compose a faith other than that defined by the holy fathers at Nicaea.",
            "Faith"),
        CouncilCanonSeedEntry("ephesus-431", 2, "Deposition of Nestorius",
            "Nestorius is deposed from the episcopate and from all priestly communion.",
            "Heresy"),
        CouncilCanonSeedEntry("ephesus-431", 3, "Celestine's judgment",
            "The judgment of Pope Celestine against Nestorius is confirmed.",
            "Primacy"),
        CouncilCanonSeedEntry("ephesus-431", 4, "John of Antioch",
            "John of Antioch and those who did not condemn Nestorius are given until the next session to conform.",
            "Discipline"),
        CouncilCanonSeedEntry("ephesus-431", 5, "Theotokos",
            "The title Theotokos (Mother of God) for the Virgin Mary is affirmed against Nestorian teaching.",
            "Christology"),
        CouncilCanonSeedEntry("ephesus-431", 6, "Deposition of non-compliant bishops",
            "Bishops who do not subscribe to the council's decisions shall be deposed.",
            "Discipline"),
        CouncilCanonSeedEntry("ephesus-431", 7, "Cyril's third letter",
            "The third letter of Cyril to Nestorius is approved as orthodox.",
            "Faith"),
        CouncilCanonSeedEntry("ephesus-431", 8, "Prohibition of new creeds",
            "No one shall produce, write, or compose any faith other than that of Nicaea.",
            "Faith"),

        // Council of Chalcedon (451) - selected key canons
        CouncilCanonSeedEntry("chalcedon-451", 1, "Faith of Nicaea and Constantinople",
            "The faith of the 318 fathers at Nicaea and the 150 at Constantinople is reaffirmed. Eutyches and Dioscorus are condemned.",
            "Faith"),
        CouncilCanonSeedEntry("chalcedon-451", 2, "Simony",
            "Those ordained for money shall be deposed, along with those who ordained them.",
            "Ordination"),
        CouncilCanonSeedEntry("chalcedon-451", 3, "Monastic exemption",
            "Monks shall not control property or engage in secular business. They are subject to the bishop.",
            "Monasticism"),
        CouncilCanonSeedEntry("chalcedon-451", 4, "Monastery foundations",
            "Monasteries once consecrated shall remain so. No secular building may be erected on the site.",
            "Monasticism"),
        CouncilCanonSeedEntry("chalcedon-451", 5, "Bishops and monasteries",
            "Bishops shall not ordain clergy for villages without the consent of the bishop of the city.",
            "Jurisdiction"),
        CouncilCanonSeedEntry("chalcedon-451", 6, "Clergy transfer",
            "No one shall be ordained absolutely, but only for a specific church, city, or village.",
            "Ordination"),
        CouncilCanonSeedEntry("chalcedon-451", 7, "Clergy and military",
            "Clergy or monks who join the military or accept secular office shall be deposed.",
            "Clergy conduct"),
        CouncilCanonSeedEntry("chalcedon-451", 8, "Charitable institutions",
            "Charitable institutions under the bishop shall be administered by a steward appointed by the bishop.",
            "Administration"),
        CouncilCanonSeedEntry("chalcedon-451", 9, "Court jurisdiction",
            "Clergy may bring ecclesiastical cases before the bishop. Secular courts may not interfere.",
            "Jurisdiction"),
        CouncilCanonSeedEntry("chalcedon-451", 10, "Multiple appointments",
            "No one shall be enrolled in two churches. Bishops and clergy shall serve only one church.",
            "Clergy conduct"),

        // Second Council of Constantinople (553) - Three Chapters
        CouncilCanonSeedEntry("constantinople-553", 1, "Condemnation of Three Chapters",
            "The Three Chapters (writings of Theodore of Mopsuestia, Theodoret, and Ibas) are condemned as Nestorian.",
            "Christology"),
        CouncilCanonSeedEntry("constantinople-553", 2, "Origenism",
            "Origen and his errors are anathematized.",
            "Heresy"),
        CouncilCanonSeedEntry("constantinople-553", 3, "Faith of Chalcedon",
            "The Chalcedonian Definition is affirmed. The condemnation of the Three Chapters does not undermine Chalcedon.",
            "Faith"),

        // Third Council of Constantinople (680-681) - Monothelitism
        CouncilCanonSeedEntry("constantinople-680", 1, "Two wills of Christ",
            "Christ has two natural wills and two natural operations, without division. Monothelitism and Monoenergism are condemned.",
            "Christology"),
        CouncilCanonSeedEntry("constantinople-680", 2, "Deposition of Monothelites",
            "Honorius of Rome, Sergius, Pyrrhus, Paul, and Peter of Constantinople, and Cyrus of Alexandria are condemned for Monothelitism.",
            "Heresy"),

        // Second Council of Nicaea (787) - Icon veneration
        CouncilCanonSeedEntry("nicaea-787", 1, "Restoration of icons",
            "The veneration of icons is restored. Those who reject the veneration of icons are anathematized.",
            "Icons"),
        CouncilCanonSeedEntry("nicaea-787", 2, "Episcopal elections",
            "Bishops shall be chosen by the metropolitan and provincial bishops. Secular authority may not impose bishops.",
            "Ordination"),
        CouncilCanonSeedEntry("nicaea-787", 3, "Monasteries",
            "Monasteries once consecrated shall remain monasteries. Secular use is forbidden.",
            "Monasticism"),
        CouncilCanonSeedEntry("nicaea-787", 4, "Episcopal consecration",
            "A bishop shall be consecrated by his metropolitan with the participation of neighboring bishops.",
            "Ordination"),
        CouncilCanonSeedEntry("nicaea-787", 5, "Deposition of Iconoclast bishops",
            "Bishops who taught against icons and were deposed shall not be restored.",
            "Discipline"),
        CouncilCanonSeedEntry("nicaea-787", 6, "Clerical formation",
            "Candidates for ordination shall be properly instructed before ordination.",
            "Ordination"),
        CouncilCanonSeedEntry("nicaea-787", 7, "Relics and altars",
            "Relics shall be placed in new churches. Liturgy may not be celebrated without relics.",
            "Liturgy"),
        CouncilCanonSeedEntry("nicaea-787", 8, "Iconoclast clergy",
            "Clergy who became Iconoclasts and then repented shall be received as laymen.",
            "Penance"),

        // Synod of Elvira (306) - selected canons
        CouncilCanonSeedEntry("elvira-306", 1, "Idolatry",
            "Those who sacrifice to idols after baptism shall not receive communion even at death.",
            "Penance"),
        CouncilCanonSeedEntry("elvira-306", 2, "Chastity",
            "Bishops, presbyters, and deacons shall abstain from their wives.",
            "Clergy conduct"),
        CouncilCanonSeedEntry("elvira-306", 3, "Adultery",
            "Women who commit adultery shall be excluded from communion until the end of life.",
            "Penance"),

        // Synod of Ancyra (314)
        CouncilCanonSeedEntry("ancyra-314", 1, "Lapsed during persecution",
            "Those who sacrificed during persecution shall spend the rest of their lives as hearers.",
            "Penance"),
        CouncilCanonSeedEntry("ancyra-314", 2, "Marriage after ordination",
            "Those who married after ordination shall be deposed.",
            "Clergy conduct"),

        // Council of Sardica (343)
        CouncilCanonSeedEntry("sardica-343", 1, "Appeal to Rome",
            "A bishop deposed by his province may appeal to the bishop of Rome.",
            "Appeals"),
        CouncilCanonSeedEntry("sardica-343", 2, "Episcopal transfer",
            "A bishop shall not transfer from one see to another.",
            "Jurisdiction"),

        // Synod of Laodicea (363)
        CouncilCanonSeedEntry("laodicea-363", 1, "Canonical books",
            "Only canonical books of the Old and New Testaments shall be read in church.",
            "Scripture"),
        CouncilCanonSeedEntry("laodicea-363", 2, "Sunday observance",
            "Christians shall not Judaize by resting on the Sabbath but shall work, honoring the Lord's Day.",
            "Liturgy"),

        // Council of Orange II (529) - against Semi-Pelagianism
        CouncilCanonSeedEntry("orange-529", 1, "Grace and free will",
            "Through the sin of Adam, human nature was so wounded that no one can turn to God by their own strength. Grace precedes good will.",
            "Grace"),
        CouncilCanonSeedEntry("orange-529", 2, "Predestination",
            "God prepares the will so that we may believe. Faith itself is a gift of God.",
            "Grace"),
        CouncilCanonSeedEntry("orange-529", 3, "Baptism of infants",
            "Infants are baptized for the remission of sins. The sin of Adam is transmitted to all.",
            "Baptism"),

        // Quinisext Council / Council in Trullo (692)
        CouncilCanonSeedEntry("quinisext-council-trullo-692", 1, "Faith of previous councils",
            "The faith of the six ecumenical councils is affirmed. No addition or subtraction is permitted.",
            "Faith"),
        CouncilCanonSeedEntry("quinisext-council-trullo-692", 2, "Clerical marriage",
            "Bishops shall not live with their wives. Clergy below the rank of deacon may remain married if married before ordination.",
            "Clergy conduct"),
        CouncilCanonSeedEntry("quinisext-council-trullo-692", 3, "Simony",
            "Ordination for money is forbidden. Both the ordainer and the ordained shall be deposed.",
            "Ordination")
    )
}
